package model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataset<M extends BaseDataset<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDatasetName(java.lang.String datasetName) {
		set("dataset_name", datasetName);
	}

	public java.lang.String getDatasetName() {
		return get("dataset_name");
	}

	public void setCreatedTime(java.lang.Integer createdTime) {
		set("created_time", createdTime);
	}

	public java.lang.Integer getCreatedTime() {
		return get("created_time");
	}

}
