package model;

import model.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();
}
